spring:
  rabbitmq:
    addresses: localhost:5672
    virtual-host: vhostmq
    username: guest
    password: guest
    listener:
      simple:
        acknowledge-mode: manual
        concurrency: 1
        max-concurrency: 1
    template:
      mandatory: true
    publisher-confirms: true
nacos:
  config:
    server-addr: localhost:8848

test:
  bean:
    name: test

executor:
  thread:
    corePoolSize: 5
    maxPoolSize: 5
    queueCapacity: 9999
    threadName: "async-service-"